services:
  telegram-bot:
    build:       
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: telegram-bot
    restart: always
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - BITLY_TOKEN=${BITLY_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .env:/.env
